### ISSUE TITLE
Hosted version?

### ISSUE THREAD

**Issue by em0ney** [AnkushMahajan/workdone#1]
Hi Ankush,

Do you have a hosted version of this running somewhere?  If not, can you add some further information in your readme about what this app does and how to start up a local development version?

**Comment by AnkushMahajan** [comment]
Hi Elliot,
I am sorry i wasn't notified of the issue/comment you raised on this repository and hence couldn't reply earlier. I actually undertook this project 6 months back in a couple of days that i had off at the time. I was playing around with Ionic 2 and tried hooking it up with redux to connect with Firebase. It has social login implemented via FB and google and a basic routing. I discontinued this as I got busy building react stuff later on, but will surely be able to answer any of your follow up questions.
You can launch the project as Ionic serve , also I've added a readme file for reference

Thanks,
Ankush

**Comment by AnkushMahajan** [comment]
Closing the issue, Please open another one if you need more information.
